### ISSUE TITLE
Issue with overlay

### ISSUE THREAD

**Issue by bananabr34d** [jakehamilton/config#3]
Over the past couple days I've been digging into this config and after setting up the new partition, cloning the repo, and generating the config I'm receiving an error while testing the flake by running `nix flake check`.  There error reads 
`warning: flake output attribute 'overlay' is deprecated; use 'overlays.default' instead` (from the outputs section of the flake.nix file)
and in this state it will not install.  Given this, I proceeded with removing the overlays from the flake and references to those application throughout the repo and ultimately was able to successfully install.  I'm still very new to NixOS, so I'm not really sure how to revise those overlays to make them work, but I'd be very interested to see if you get the same results and if so, how would you correct it?

**Comment by jakehamilton** [comment]
Hi @bananabr34d :wave:

I'm not too sure I understand the problem here. Those deprecation warnings shouldn't be stopping you from using the flake. Were you getting any other output?
