### ISSUE TITLE
Multi-User?

### ISSUE THREAD

**Issue by usmcamp0811** [jakehamilton/config#8]
I'm impressed with your recent work in fully integrating standalone home-manager support. I'm curious if you might have any insights or suggestions on how to handle multi-user scenarios, specifically with LDAP. In my current setup, I rely on an LDAP user as my primary account across all systems. I adopted this approach to overcome the challenges of synchronizing user data across different distributions, which previously led to NFS permission issues. My current solution involves configuring a local user in my Nix setup and properly setting up LDAP. I then utilize home-manager's standalone mode to individually configure the LDAP user. While this method is functional, I'm exploring ways to streamline the configuration of both a local user and at least one LDAP user within my config flake (which, I've heavily borrowed from here 😀). Any thoughts or guidance would be greatly appreciated but don't want you to feel like I'm asking you to go do anything. I'm still learning Nix and just looking to see if you had any ideas. 

Thanks

**Comment by usmcamp0811** [comment]
Of course.. I muck with this all day and right after I decided to ask some questions I think I figured it out. Seems I am able to make a user config in `./homes/x86_64-linux/<username>@<fictional hostname>` and nothing complains and I can still do things like `nix run .\#homeConfigurations.mcamp@ldap.activationPackage`. 

Still curious your thoughts, but feel free to close this..

**Comment by jakehamilton** [comment]
Hey there! I'm not too familiar with this kind of setup unfortunately. I think you may have found a solution that works (even if it's not perfect) with custom homes and executing the activation script manually.

I have had multi-user on my mind, but beyond the current support in Snowfall Lib I don't think anything will be changing for a while.

**Comment by adarah** [comment]
I don't quite get the details of OPs setup, but I managed to get two different home-manager users working in the same host with the dev branch of snowfall lib: https://github.com/snowfallorg/lib/issues/44

**Comment by jakehamilton** [comment]
I'm going to close this issue out. As @adarah mentioned, the dev branch of Snowfall Lib (and therefore the v3 release when it is out) supports home-manager more fully and can enable a multi-user setup. I don't have plans to do so in my config since I'm the only user, but I believe that all the tools are in place to make it happen now!
